# Generated by Django 5.1.1 on 2024-09-14 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellido')),
                ('rut', models.CharField(max_length=20, verbose_name='RUT')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Teléfono de contacto')),
                ('company', models.CharField(max_length=100, verbose_name='Institución a la que representa')),
                ('region', models.CharField(max_length=100, verbose_name='Región')),
                ('data_sharing_consent', models.BooleanField(default=False, verbose_name='Autoriza que sus datos sean compartidos con empresas participantes de este evento')),
                ('track_of_interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estadodigital.track', verbose_name='Track de su interés')),
            ],
        ),
    ]
