# Generated by Django 5.1.1 on 2024-09-24 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadodigital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='position',
            field=models.CharField(default=1, max_length=100, verbose_name='Cargo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='track',
            name='schedule',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
