# Generated by Django 5.1.1 on 2024-09-24 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadodigital', '0002_contact_position_track_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='track_of_interest',
        ),
        migrations.AddField(
            model_name='contact',
            name='track_of_interest',
            field=models.ManyToManyField(to='estadodigital.track', verbose_name='Track de su interés'),
        ),
    ]
