# Generated by Django 5.1.1 on 2024-09-24 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadodigital', '0003_remove_track_schedule_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='track_of_interest',
        ),
        migrations.DeleteModel(
            name='Track',
        ),
        migrations.AddField(
            model_name='contact',
            name='track_of_interest',
            field=models.JSONField(default=1, verbose_name='Track de su interés'),
            preserve_default=False,
        ),
    ]
